#
#	Connection configuration file ( pg_service.conf Like tnsnames.ora )
#

#[postgres]
#dbname=postgres
#user=postgres

[dev]
host=127.0.0.1
port=5432
user=test
dbname=test
sslmode=require
channel_binding=prefer

[devadm]
host=127.0.0.1
#port=5432
user=core
dbname=test
#sslmode=require
#channel_binding=disable